name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Gera todos os dias à meia-noite
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: duar-franc
          outputs: |
            ./output/github-contribution-grid-snake-dark.svg

      - name: Push to output branch
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate contribution grid snake"
          add: "output/github-contribution-grid-snake-dark.svg"
